stages:
- name: Build
  steps:
  - runScriptConfig:
      image: node:current-alpine3.12
      shellScript: nodejs --version && npm --version
    when:
      branch:
        include:
        - main
      event:
        include:
        - pull_request
        - push
  when:
    branch:
      include:
      - main
    event:
      include:
      - push
      - pull_request
- name: Build and Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: modelisgroup/productivity-frontend:prod-v1
      pushRemote: true
      registry: index.docker.io
    env:
      PLUGIN_INSECURE: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 1
branch:
  include:
  - main
  exclude:
  - develop
notification: {}
